#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Snake.Android.Resource", IsApplication=true)]

namespace Snake.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_in_back = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_out = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_out_back = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int MvxBind = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxDropDownItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int MvxItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int MvxLang = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int MvxTemplate = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int fontPath = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int Black = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Green = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06001e
			public const int GameButtonPadding = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int GameInfoMargin = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int GameViewBorderWidth = 2131099681;
			
			// aapt resource value: 0x7f06001b
			public const int NewGameButtonHorizontalPadding = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int NewGameButtonVerticalPadding = 2131099676;
			
			// aapt resource value: 0x7f060020
			public const int PixelSize = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int PopUpTextPadding = 2131099677;
			
			// aapt resource value: 0x7f060002
			public const int Text18 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Text20 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Text21 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Text22 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Text23 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Text24 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Text25 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Text26 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Text27 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int Text28 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int Text29 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int Text30 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int Text31 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int Text32 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int Text34 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int Text36 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int Text38 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int Text40 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int Text44 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int Text46 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int Text48 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int Text50 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int Text54 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int Text58 = 2131099673;
			
			// aapt resource value: 0x7f060000
			public const int Text6 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Text66 = 2131099649;
			
			// aapt resource value: 0x7f06001a
			public const int Text70 = 2131099674;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int design_arrow_down = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int design_arrow_left = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int design_arrow_right = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int design_arrow_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int design_close_popup = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int design_dot = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int design_game_board_border = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int design_new_game = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int design_pause = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int design_popup = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int design_snake_dot = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int design_splash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ShapeGameView = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int BottomContent = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int GamePanel = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int LeftArrow = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int MvxBindingTagUnique = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int RightArrow = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int StartGameContent = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int TopContent = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Layout_GameActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Layout_SplashActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Layout_StartActivity = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int Easy = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int Hard = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int HighScores = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int Level = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int Medium = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int NewGame = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int Quit = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int Restart = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int Score = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int easy = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int high = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int medium = 2131230723;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f09000c
			public const int GameInfoStyle = 2131296268;
			
			// aapt resource value: 0x7f090006
			public const int NoHeightStretchedHorizontallyView = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int NoHeightWrappedView = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int NoWidthStretchedHorizontallyView = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int NoWidthStretchedVerticallyView = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int NoWidthWrappedView = 2131296260;
			
			// aapt resource value: 0x7f09000a
			public const int PointsLabelView = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int PointsView = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int StartGamePopUpItem = 2131296267;
			
			// aapt resource value: 0x7f090001
			public const int StretchedHorizontallyView = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int StretchedVerticallyView = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int StretchedView = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int WrappedView = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] Typeface = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int Typeface_fontPath = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
